//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Jewelries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jewelries()
        {
            this.Accessories = new HashSet<Accessories>();
        }
    
        public int JewelriesID { get; set; }
        [Display(Name = "Jewelry Name")]
        public string JName { get; set; }
        [Display(Name = "Jewelry Type")]
        public string JType { get; set; }
        [Display(Name = "Metal")]
        public string JMetal { get; set; }
        [Display(Name = "Occasion")]
        public string JOccasion { get; set; }
        public string JPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accessories> Accessories { get; set; }
    }
}
