//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shoes()
        {
            this.Wardrobes = new HashSet<Wardrobes>();
        }
    
        public int ShoesID { get; set; }
        public string ShoesName { get; set; }
        public string ShoesType { get; set; }
        public string ShoesColor { get; set; }
        public string ShoesSeason { get; set; }
        public string ShoesOccasion { get; set; }
        public string ShoesPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wardrobes> Wardrobes { get; set; }
    }
}
