//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeProjectEntities : DbContext
    {
        public WardrobeProjectEntities()
            : base("name=WardrobeProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessories> Accessories { get; set; }
        public virtual DbSet<Bottoms> Bottoms { get; set; }
        public virtual DbSet<Hats> Hats { get; set; }
        public virtual DbSet<Jewelries> Jewelries { get; set; }
        public virtual DbSet<Shoes> Shoes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tops> Tops { get; set; }
        public virtual DbSet<Wardrobes> Wardrobes { get; set; }
    }
}
